#!/usr/bin/perl
#
# Copyright (C) 2014 and later, Indie Computing Corp. All rights reserved. License: see package.
#

use strict;
use warnings;

use UBOS::Utils;
use UBOS::Logging;

if( @ARGV != 2 ) {
    error( 'Wrong number of arguments:', @ARGV );
    exit( 1 );
}

my $operation = $ARGV[0];
my $file      = $ARGV[1];

if( $operation eq 'undeploy' ) {
    my $json = UBOS::Utils::readJsonFromFile( $file );

    my $dir = $json->{appconfig}->{apache2}->{dir};
    my $out = "$dir/file";

    UBOS::Utils::deleteFile( $out );
}

exit( 0 );

1;
