#!/usr/bin/perl
#

use strict;

use UBOS::Utils;

my $dir  = $config->getResolve( 'appconfig.apache2.dir' );
my $file = "$dir/file";


if( 'deploy' eq $operation ) {
    my @keys = $config->keys();

    my $content = "# Generated by workout-perlscript1\n";
    foreach my $key ( @keys ) {
        $content .= sprintf( '%-40s%-42s\${%s}', $key, $config->getResolve( $key ), $key ) . "\n";
    }
    UBOS::Utils::saveFile( "$dir/file", $content );
}

if( 'undeploy' eq $operation ) {
    if( -e $file ) {
        UBOS::Utils::deleteFile( $file )
    }
}

1;
